server:	server.c network.c network.h
	gcc server.c network.c -o server -g
name:	nameserver.c network.c network.h
	gcc nameserver.c network.c -o name -g
client:	client.c network.c network.h
	gcc client.c network.c -o client -g
